begin: "2000-01-01 00:00:00"
end: "2000-01-01 23:59:59"
log_file: "sample_inertial.csv"
init_direct: 0
init_pos: [0, 0]
result_file_name:

enable_clear_map: True
enable_save_img: False
enable_save_video: False
frame_rate: 1
map_conf_file: sample.yaml
map_img_file: sample.pgm
map_show_range:

truth_log_file:

enable_write_conf: False

gyro_drift: 0
rotate_ax: 3

default_speed: 1
max_status_interval: 0.5
min_step_interval: 0.5
stature: 1.7
step_len_coef: 0.42
step_begin_acc_thresh: 1.05
pos_peak_acc_thresh: 1.11
neg_peak_acc_thresh: 0.93
step_end_acc_thresh: 0.97

freq: 100
pdr_win_stride: 0.1

# tentation
win_size: 2.5
enable_draw_beacons: False
map_show_policy: 2
win_stride: 1
direct_sd: 1
max_particle_stride: 25
rand_pos_range: 375
lost_resample_policy: 1
dist_sd: 50
el_correction: 2
estim_pos_policy: 1
neg_weight_coef: 0
propag_coef: 5.5
win_policy: 1
